### ISSUE TITLE
Display invalid status label color in some voting page

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#114]
**Describe the bug**
The voting page for voting prime minister shows an invalid status label text color.

**To Reproduce**
1. Go to the voting [เลือก พิธา ลิ้มเจริญรัตน์ เป็นนายกฯ](https://parliamentwatch.wevis.info/votings/%E0%B9%80%E0%B8%A5%E0%B8%B7%E0%B8%AD%E0%B8%81-%E0%B8%9E%E0%B8%B4%E0%B8%98%E0%B8%B2-%E0%B8%A5%E0%B8%B4%E0%B9%89%E0%B8%A1%E0%B9%80%E0%B8%88%E0%B8%A3%E0%B8%B4%E0%B8%8D%E0%B8%A3%E0%B8%B1%E0%B8%95%E0%B8%99%E0%B9%8C-%E0%B9%80%E0%B8%9B%E0%B9%87%E0%B8%99%E0%B8%99%E0%B8%B2) and [เลือก เศรษฐา ทวีสิน เป็นนายกฯ](https://parliamentwatch.wevis.info/votings/%E0%B9%80%E0%B8%A5%E0%B8%B7%E0%B8%AD%E0%B8%81-%E0%B9%80%E0%B8%A8%E0%B8%A3%E0%B8%A9%E0%B8%90%E0%B8%B2-%E0%B8%97%E0%B8%A7%E0%B8%B5%E0%B8%AA%E0%B8%B4%E0%B8%99-%E0%B9%80%E0%B8%9B%E0%B9%87%E0%B8%99%E0%B8%99%E0%B8%B2%E0%B8%A2%E0%B8%81%E0%B8%AF)
2. Scroll down to "ผลการลงมติ" > "ผลการลงมติรายสังกัด" to see the bug

**Expected behavior**
The status label text color should be the same as the corresponding status.

**Screenshots**

![image](https://github.com/user-attachments/assets/f0683f14-e618-4057-adf3-d38ffd8f8a3c)

**Additional context**
- Check out from and open PR to `main`
- Voting page entry point source code: `src/routes/votings/[id]/+page.svelte`

**Comment by svnnynior** [comment]
Since my PR (#112) is kind of blocked with some pending questions atm. Can I pick this up as well?

**Comment by Th1nkK1D** [comment]
@svnnynior thank you for your enthusiasm, I already got the answers, will reply to the issue soon as possible so you don't hold many issues at the same time 🙏

**Comment by nutchanon-c** [comment]
I think I found where to fix this. It's a pretty simple fix. Can assign me if you want.

**Comment by nutchanon-c** [comment]
Opened PR if necessary https://github.com/wevisdemo/parliament-watch/pull/124

**Comment by Th1nkK1D** [comment]
@nutchanon-c  You are so fast! 🔥 I'll review you PRs tomorrow
