### ISSUE TITLE
Make votings and bills tables show 50 items per page

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#115]
**Is your feature request related to a problem? Please describe.**
The current table on the [Assembly's voting page](https://parliamentwatch.wevis.info/assemblies/%E0%B8%AA%E0%B8%A0%E0%B8%B2%E0%B8%9C%E0%B8%B9%E0%B9%89%E0%B9%81%E0%B8%97%E0%B8%99%E0%B8%A3%E0%B8%B2%E0%B8%A9%E0%B8%8E%E0%B8%A3-26/votes) and [Bills explore page](https://parliamentwatch.wevis.info/bills/explore) shows 10 items per page, which makes users need to click to the next page often to browse older items. 

![image](https://github.com/user-attachments/assets/7b9dbac5-521c-4a53-b4af-ccf9e9dcaf06)

![image](https://github.com/user-attachments/assets/6c1b284a-78b3-41f9-b193-32a78f9c5fbf)

**Describe the solution you'd like**
Increase the number of items per page to 50.

**Additional context**
- Check out from and open PR to `main`
- Assembly's voting page entry point file: `src/routes/assemblies/[id]/votes/+page.svelte` 
- Bill explores page entry point file: `src/routes/bills/explore/+page.svelte`

**Comment by nutchanon-c** [comment]
I'd like to give it a try.

**Comment by nutchanon-c** [comment]
opened PR https://github.com/wevisdemo/parliament-watch/pull/122
