### ISSUE TITLE
Add tooltips in the assembly member chart

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#116]
**Is your feature request related to a problem? Please describe.**
As a user, I want to see a tooltip when I hover a dot in the chart so that I can find out who they are when the dots look significant.

Representative and Senate chart:
![image](https://github.com/user-attachments/assets/7c9f3304-eb9d-4f81-9c91-80d3960bca19)

Cabinet chart:
![image](https://github.com/user-attachments/assets/e9142b27-749c-4392-88ea-3e6ba59be66f)

**Describe the solution you'd like**

- Given I visited an assembly page, either [representative](https://parliamentwatch.wevis.info/assemblies/%E0%B8%AA%E0%B8%A0%E0%B8%B2%E0%B8%9C%E0%B8%B9%E0%B9%89%E0%B9%81%E0%B8%97%E0%B8%99%E0%B8%A3%E0%B8%B2%E0%B8%A9%E0%B8%8E%E0%B8%A3-26)., [senate](https://parliamentwatch.wevis.info/assemblies/%E0%B8%A7%E0%B8%B8%E0%B8%92%E0%B8%B4%E0%B8%AA%E0%B8%A0%E0%B8%B2-12), or [cabinet](https://parliamentwatch.wevis.info/assemblies/%E0%B8%84%E0%B8%93%E0%B8%B0%E0%B8%A3%E0%B8%B1%E0%B8%90%E0%B8%A1%E0%B8%99%E0%B8%95%E0%B8%A3%E0%B8%B5-64)
- When I hover over a dot representing an assembly member
- Then I should see the following info
   - Name of the person
   - Party Name

![image](https://github.com/user-attachments/assets/121a4a78-dfbb-481d-877d-9a6185947253)

**Implementation suggestion**
- Use [Carbon Tooltip Component](https://svelte.carbondesignsystem.com/components/Tooltip) should be the easiest solution if it works.
- If not, recommend using [MeltUI headless tooltip](https://melt-ui.com/docs/builders/tooltip)

**Additional context**
- Check out from and open PR to `main`
- Representatives and the Senate use SVG, while the Cabinet uses a simple HTML/CSS layout.
- Assembly page entry file: `src/routes/assemblies/[id]/+page.svelte`

**Comment by greatng** [comment]
I would like to do this, could you please assign it to me?. It should take a couple days since I don't have much experience in Svelte.

**Comment by Th1nkK1D** [comment]
@greatng don't worry and take your time! Most of the contributors also new to Svelte and we are here to help if you are stuck with anything ;)
