### ISSUE TITLE
Add story for PromiseCard

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#120]
**Is your feature request related to a problem? Please describe.**
Component `src/components/PromiseList/PromiseCard.svelte` can be used in many places, but there is no story file describing this component yet.

**Describe the solution you'd like**
- No need to change the component code.
- Create a story file `src/components/PromiseList/PromiseCard.story.svelte`

**Additional context**
- Check out from and open PR to `promises/main`
- We use [Histoire](https://histoire.dev/guide/svelte3/stories.html) for the frontend component catalog, each described by a story file.
- Start histoire dev server with `yarn story:dev`
- Split `isList` value into separated variants
- Add controls for all the props except `isList`
- If you need to mock data from the props, you can take sample data from `src/mocks/data/promise.ts`

**Comment by badgooooor** [comment]
Let's go 🙌

**Comment by badgooooor** [comment]
I've tried implementing story with seperated control props but it's not rerender the component inside the story. Here's source code right now, https://pastebin.com/FsZL5hZT.
<img width="1360" alt="image" src="https://github.com/user-attachments/assets/b8c772be-350d-46db-99e6-c755f38d1411">

If it's not work, would seperating variant as status and also list will do to fulfil this story too?

**Comment by Th1nkK1D** [comment]
> I've tried implementing story with seperated control props but it's not rerender the component inside the story. Here's source code right now, https://pastebin.com/FsZL5hZT

I tried your code and my machine and found this error on the console:
![image](https://github.com/user-attachments/assets/556188b0-90b1-44ca-bc56-3d022740c3eb)

When there is an error, JS stop working including the rerender logic.

The issue come from these lines:
```svelte
$: latestProgressDate = new Date(dateString);

$: promiseSummary = {
  id: 'PST-33',
  status,
  statements,
  keywords,
  categories,
  party,
  latestProgressDate,
};
```
`promiseSummary` depends on the `latestProgressDate` but when both are reactive with `$`, it got executed at the same time (even though `latestProgressDate` progess line come first, Svelte doesn't guarantee to assign it first). So on the first tick, `latestProgressDate` is not completly assigned yet, `promiseSummary.latestProgressDate` become undefined and caused the error.

Combine into one reactive variable solved the problem:

```svelte
$: promiseSummary = {
  id: 'PST-33',
  status,
  statements,
  keywords,
  categories,
  party,
  latestProgressDate: new Date(dateString),
};
```
