### ISSUE TITLE
Add story for PromiseList

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#121]
**Is your feature request related to a problem? Please describe.**
Component `src/components/PromiseList/PromiseList.svelte` can be used in many places, but there is no story file describing this component yet.

**Describe the solution you'd like**
- No need to change the component code.
- Create a story file `src/components/PromiseList/PromiseList.svelte`

**Additional context**
- Check out from and open PR to `promises/main`
- We use [Histoire](https://histoire.dev/guide/svelte3/stories.html) for the frontend component catalog, each described by a story file.
- Start histoire dev server with `yarn story:dev`
- Split `isList` value into separated variants
- Add controls for all the props except `isList`
- If you need to mock data from the props, you can take sample data from `src/mocks/data/promise.ts`

**Comment by SupeemAFK** [comment]
Has anyone done this yet? I can do it.

**Comment by Th1nkK1D** [comment]
> Has anyone done this yet? I can do it.

Yes! you can take it ;)

**Comment by SupeemAFK** [comment]
![image](https://github.com/user-attachments/assets/45c45692-a8ff-44b0-b2b7-8da5e1069964)
Sorry but I don't see props in promiseList except summaries. Do I have to create controls for summaries but isn't a single summary is already described in promiseCard? I'm confused what should be in controls should it be sortBy?

**Comment by Th1nkK1D** [comment]
@SupeemAFK My bad, I misread the code and thought `isList` was a prop 🙏. Let's not change the component logic if it is unnecessary. I would say the only control for this component would be `summaries`, even though it was already described in `PromiseCard`. Control makes it visible to other people what the props are for each component, and `summaries` are the only props here.

Even though this component has one prop described by another component's story, would it still worry writing this story? Yes. `PromiseList` has many behaviors like sorting and list view worth showing out in the storybook, and has a high potential to be reused again in the future. What do you think?

**Comment by Th1nkK1D** [comment]
One more thing, we just merged `promise/main` branch to `main` yesterday for the launching event. So I suggest you check out from `main` and open PR targeting `main` instead.

**Comment by SupeemAFK** [comment]
> @SupeemAFK My bad, I misread the code and thought `isList` was a prop 🙏. Let's not change the component logic if it is unnecessary. I would say the only control for this component would be `summaries`, even though it was already described in `PromiseCard`. Control makes it visible to other people what the props are for each component, and `summaries` are the only props here.
> 
> Even though this component has one prop described by another component's story, would it still worry writing this story? Yes. `PromiseList` has many behaviors like sorting and list view worth showing out in the storybook, and has a high potential to be reused again in the future. What do you think?

That's great! I think it's a good practice too. One more thing Do I have to change isList to props in PromiseList component and if not How do I split isList value into separated variants

**Comment by Th1nkK1D** [comment]
Nice to hear from you!

> Do I have to change isList to props in PromiseList component and if not How do I split isList value into separated variants

You don't need to change it to props since it is an internal state. And when it is not a props, we can't control the variant from the outside (we put the component in a different `Hst.Varient` with different props) so no need for variants here too.
