### ISSUE TITLE
Promise: include promises in SearchResult

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#129]
~~This issue is based on the unreleased promise feature. Checkout and create PR on `promise/main` branch.~~

**Is your feature request related to a problem? Please describe.**
We introduced a new promise section on our website (`/promises`), but the search function is not showing promises in the results yet.

**Describe the solution you'd like**
Promise group should be shown at the bottom of the `SearchResult`
- Group title = "คำสัญญา"
- Group icon = `src/components/icons/PromiseIcon.svelte`
- Item inside should look exactly like `การลงมติ` and `การออกกฎหมาย`
   - Should use `src/components/PromiseDetail/PromiseStatusTag.svelte` component for status

![image](https://github.com/user-attachments/assets/1c66bbbc-216c-46d7-a701-70463b3e2022)

**Additional context**
- Don't need to worry about main site integration. You can work in the Histoire's storybook with `yarn run story:dev` and look for `SearchResult`
- Source code file as a starting point
   - `SearchResult` component: `src/components/SearchResult/SearchResult.svelte`
   - `SearchResult` story file:  `src/components/SearchResult/SearchResult.story.svelte`
- You can add this mock data in the story file:
```ts
const searchResults: SearchResults = {
	// ...
	bills: [
		{ heading: 'โครงการ 1 อำเภอ 1 ทุน (ODOS: One District One Scholarship)', promiseStatus: PromiseStatus.notStarted, url: '#m' },
		{ heading: '“รถไฟฟ้า กทม.” 20 บาทตลอดสาย', promiseStatus: PromiseStatus.inProgress, url: '#n' },
	]
}
```
- Making changes to any related files if needed

**Comment by svnnynior** [comment]
I can pick this one up next na. Feel free to assign it to me.

**Comment by Th1nkK1D** [comment]
> I can pick this one up next na. Feel free to assign it to me.

Bro u r so fit

> Edit: One question - Are we still using the `promise/main` branch? it's written in the description of this issue.

I forgot to update it, let's do it from `main` now.
