### ISSUE TITLE
Promise: Missing numbers of ministers of the parties

### ISSUE THREAD

**Issue by itwasup** [wevisdemo/parliament-watch#131]
**Describe the bug**
The numbers of ministers of the parties are missing.
![image](https://github.com/user-attachments/assets/32371d8a-8921-47ef-b6ee-b2bbddf95a60)

**To Reproduce**
1. Go to https://promise-main.parliament-watch.pages.dev/promises

**Expected behavior**
Show the number of ministers as in the design
![image](https://github.com/user-attachments/assets/c90722f9-745a-4e33-b1a5-2671b9de32af)
https://www.figma.com/design/ywiKyd0XIgDXf8crX4aoYE/Design_Phase1-2-%5BPromise-Tracker%5D?node-id=4552-9076&t=IHXSC18sFBO2oZ1e-4

**Comment by Th1nkK1D** [comment]
## Notes for contributor
- This issue is based on the unreleased promise feature. Checkout and create PR on `promise/main` branch.
- The entry source code file: `src/routes/promises/+page.svelte` for the page UI and `src/routes/promises/+page.server.ts` for the data preparation.
