### ISSUE TITLE
Promise: Hide 'See All' link when there are no promise with the status

### ISSUE THREAD

**Issue by itwasup** [wevisdemo/parliament-watch#133]
**Is your feature request related to a problem? Please describe.**
It is useless to show the 'ดูทั้งหมด' (See All) link when there is no Promise with the status
<img width="1137" alt="Screenshot 2567-10-18 at 15 02 18" src="https://github.com/user-attachments/assets/38c005ac-0fc0-49a9-82e6-89971a53bdc2">

**Describe the solution you'd like**
- Given there are no promises with the status
- When I view the status section
- Then I should not see
  - the text 'เช่น'
  - the link 'ดูทั้งหมด'

**Comment by Th1nkK1D** [comment]
## Notes for contributor
- This issue is based on the unreleased promise feature. Checkout and create PR on `promise/main` branch.
- The entry source code file: `src/routes/promises/+page.svelte` for the page UI and `src/routes/promises/+page.server.ts` for the data preparation.

**Comment by greatng** [comment]
Let me do this and 134

**Comment by Th1nkK1D** [comment]
@greatng Thank you! However, there is one piece of feedback left for your previous PR #127, which you may have missed. When that PR is merged I can assign you a new issue, maybe these 2 if it's still available.
