### ISSUE TITLE
Promise: Hide the Status's section when there are no promises with the status

### ISSUE THREAD

**Issue by itwasup** [wevisdemo/parliament-watch#134]
**Is your feature request related to a problem? Please describe.**
It is unnecessary to talk about the status that no items are referring to it.
<img width="1141" alt="Screenshot 2567-10-18 at 15 11 49" src="https://github.com/user-attachments/assets/c9b02de2-9814-4740-a907-4b7e853e4118">

**Describe the solution you'd like**
- Given the status has no promises referring to it
- When I view the section
- Then the section should be hidden (the whole gray box)

**Comment by Th1nkK1D** [comment]
## Notes for contributor
- This issue is based on the unreleased promise feature. Checkout and create PR on `promise/main` branch.
- The entry source code file: `src/routes/promises/+page.svelte` for the page UI and `src/routes/promises/+page.server.ts` for the data preparation.

**Comment by Th1nkK1D** [comment]
@greatng looks like I can't assign external people if they don't comment on the issue first.

**Comment by greatng** [comment]
✋🏼 I'm up.
