### ISSUE TITLE
Promise: Change the copy from 'เคลื่อนไหวล่าสุด' to 'อัปเดตล่าสุด'

### ISSUE THREAD

**Issue by itwasup** [wevisdemo/parliament-watch#136]
**Describe the bug**
The copy 'เคลื่อนไหวล่าสุด' sounds confusing when the promise has the status 'ไม่พบความเคลื่อนไหว'
![image](https://github.com/user-attachments/assets/ed27c09e-723d-4fd3-bdca-f6233800a1f5)

**Suggested Solution**
Change the label from 'เคลื่อนไหวล่าสุด' to 'อัปเดตล่าสุด' instead.

**Comment by Th1nkK1D** [comment]
## Notes for contributor
- This issue is based on the unreleased promise feature. Checkout and create PR on `promise/main` branch.
- The entry source code file: `src/routes/promises/+page.svelte` for the page UI`
