### ISSUE TITLE
Promise: The status's definition is missing

### ISSUE THREAD

**Issue by itwasup** [wevisdemo/parliament-watch#137]
**Describe the bug**
The status's definition is missing
![image](https://github.com/user-attachments/assets/b9d7d514-8006-4b31-a849-21c7adcd15e0)

**To Reproduce**
1. Go to https://promise-main.parliament-watch.pages.dev/promises/PST-16

**Expected behavior**
Show the definition as follows

- **รอคำชี้แจงเพิ่มเติม**: เราพบว่าคำสัญญานี้มีความคลุมเครือและกำลังอยู่ในระหว่างการขอคำชี้แจงเพิ่มเติม
- **ไม่พบความเคลื่อนไหว:** เราไม่พบข้อมูลความเคลื่อนไหวที่เกี่ยวกับคำสัญญานี้
- **กำลังดำเนินการ:** เราพบข้อมูลความคืบหน้า แต่ยังไม่บรรลุเป้าหมายที่ได้สัญญาไว้
- **ดำเนินการแล้ว:** เราพบข้อมูลความคืบหน้า และข้อมูลที่ชี้ว่าได้บรรลุเป้าหมายที่ได้สัญญาไว้แล้ว
- **เลิกดำเนินการ:** เราพบข้อมูลความคืบหน้า ที่ชี้ว่ามีการเลิกดำเนินการเพื่อบรรลุเป้าหมายตามคำสัญญานี้แล้ว

**Comment by Th1nkK1D** [comment]
## Notes for contributor
- This issue is based on the unreleased promise feature. Checkout and create PR on `promise/main` branch.
- The entry source code file: `src/routes/promises/[id]/+page.svelte` for the page UI and `src/routes/promises/[id]/+page.server.ts` for the data preparation.
