### ISSUE TITLE
Promise: Unable to click keyword or category tags to view similar promises

### ISSUE THREAD

**Issue by itwasup** [wevisdemo/parliament-watch#138]
**Describe the bug**
Unable to click keyword or category tags to view similar promises
![image](https://github.com/user-attachments/assets/3a4c635e-4681-4064-b6a7-096d4fc7c404)

**To Reproduce**
1. Go to https://promise-main.parliament-watch.pages.dev/promises/PST-16

**Expected behavior**

- Given the promise has a keyword tag or category tag
- When I visit the Promise Detail page and click on the tag to view similar promises
- Then, it should show me [the search results](https://promise-main.parliament-watch.pages.dev/promises/explore?category=%E0%B9%80%E0%B8%A8%E0%B8%A3%E0%B8%A9%E0%B8%90%E0%B8%81%E0%B8%B4%E0%B8%88) of all promises that have the tag -- similar to the behavior when  I click on a tag in a promise card.

**Comment by Th1nkK1D** [comment]
## Notes for contributor
- This issue is based on the unreleased promise feature. Checkout and create PR on `promise/main` branch.
- The entry source code file: `src/routes/promises/+page.svelte` for the page UI and `src/routes/promises/+page.server.ts` for the data preparation.
