### ISSUE TITLE
Upgrade Cloudflare actions in the staging workflow

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#141]
**Is your feature request related to a problem? Please describe.**
We currently use [Cloudflare Pages Actions](https://github.com/cloudflare/pages-action) in [staging workflow file](https://github.com/wevisdemo/parliament-watch/blob/main/.github/workflows/staging.yml) which is marked as deprecated.

The deployment with Pages Action frequently failed randomly, which might related to the deprecation.

**Describe the solution you'd like**
Replace Pages Actions with the [Wrangler Action](https://github.com/cloudflare/wrangler-action)

**Comment by svnnynior** [comment]
Looks interesting, I'd like to take a stab at this. Could you assign it to me?
