### ISSUE TITLE
Remove text from all bill status cards in legislative-process page

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/parliament-watch#142]
**Describe the bug**

**To Reproduce**
Go to '[https://parliamentwatch.wevis.info/legislative-process](https://parliamentwatch.wevis.info/legislative-process#%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%B0%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B8%81%E0%B8%8E%E0%B8%AB%E0%B8%A1%E0%B8%B2%E0%B8%A2)'

**Expected behavior**
Remove "_จำนวน xxxx ฉบับ_" from all bill status cards
(They are description of process with no updated data)

**Screenshots**
<img width="753" alt="image" src="https://github.com/user-attachments/assets/98bd17ea-6b19-4375-837d-7ea4ddba423f">

**Comment by Th1nkK1D** [comment]
## Notes for contributor
- Checkout and create PR on the `main` branch.
- The entry source code file for this page is: `src/routes/legislative-process/+pages.svelte`.
