### ISSUE TITLE
Change text from "มติ" to "ร่างกฎหมาย" in Bill Explore Page

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/parliament-watch#143]
**Describe the bug**
Change text from "มติ" to "ร่างกฎหมาย"

**To Reproduce**
1. Go to [สำรวจร่างกฎหมาย](https://parliamentwatch.wevis.info/bills/explore)
2. Scroll down to 'the bottom of the table'

**Screenshots**
<img width="157" alt="image" src="https://github.com/user-attachments/assets/bc866537-9cd1-432f-9f71-26aa375f03a4">

**Comment by Th1nkK1D** [comment]
## Notes for contributor
- Checkout and create PR on the `main` branch.
- The entry source code file for this page is: `src/routes/bills/explore/+pages.svelte`.
- I think the component responsible is used in many places, so you need to add a new prop (maybe `unit`) to custom this text.
