### ISSUE TITLE
"ย้ายพรรคบ่อยที่สุด" (The biggest party-hopper) is technically correct but can be misleading

### ISSUE THREAD

**Issue by bact** [wevisdemo/parliament-watch#150]
**Describe the bug**

- On the main page, there's a section called "ย้ายพรรคบ่อยที่สุด" to highlights those who switch parties the most.
- Since there are numbers of party dissolutions, the counts can be misleading (if we like to highlight those politicians that really have intentions to hop around -- because these switching are non-voluntary).

**To Reproduce**
1. Go the main page
2. Scroll down a bit to see the "นักการเมืองชุดล่าสุดที่น่าสนใจ" section
3. "ย้ายพรรคบ่อยที่สุด" is there. On 23 Oct 2024, it is [นาย คำพอง เทพาคำ](https://parliamentwatch.wevis.info/politicians/%E0%B8%84%E0%B8%B3%E0%B8%9E%E0%B8%AD%E0%B8%87-%E0%B9%80%E0%B8%97%E0%B8%9E%E0%B8%B2%E0%B8%84%E0%B8%B3)

**Expected behavior**

- Take into account that some switches are non-voluntary.
  - For example, these pairs are non-voluntary: (Thai Rak Thai -> People Power Party), (People Power Party -> Pheu Thai Party), (Move Forward Party ->  People's Party)
- MPs whose their "switching" are from those pairs should not get their "switching counter" increase
  - The pairs should have a transitive characteristics, meaning that if there are (A -> B) and (B -> C) and if Politician X got elected while he/she is in Party A and then again in Party C, this also shouldn't get counted as a switch.
  - Although, for this algorithm, there can be some edge cases for candidates who switched parties but not get elected in-between. For example, a Politician Y who got elected while he/she is in Party A, switched to Party B, failed the campaign with Party B, and go back to Party A and won, will not get counted. (But for this case, any algorithm that solely based on the elected MP information will fail to count the switching accurately anyway).

**Screenshots**

![kamphong](https://github.com/user-attachments/assets/e43deb73-5c08-4610-88ef-ab87f8d368c4)
![kamphong-details](https://github.com/user-attachments/assets/37871d84-fc36-403c-9187-469021609441)

(Computing environment irrelevant)

**Comment by fResult** [comment]
Good point krub.
Could anyone provide the *pairs of parties* that the politicians do not voluntarily switch?

**Comment by Th1nkK1D** [comment]
> Good point krub. Could anyone provide the _pairs of parties_ that the politicians do not voluntarily switch?
> 
> cc. @Th1nkK1D

I'm not sure about the other pair, I still have tech knowledge more than political lol, but this future-forward -> moving forward -> and people party is a great example. 

Moreover, our team took your issue and discussed that the whole fun-fact section is mostly unclear especially when our dataset is not complete, so we might take this section down in the next release. Until our data is complete and we have a better matrix.

**Comment by Th1nkK1D** [comment]
So if anyone wants to contribute to this. What can we do now is remove the whole section in the red box from the home page https://parliamentwatch.wevis.info/

![image](https://github.com/user-attachments/assets/0c74fa21-6311-4859-bb83-8216b0c38380)

- Remove related UI from `src/routes/+page.svelte`
- Remove related data  `src/routes/+page.server.ts`
- Other related code from other files that won't be used anymore.

**Comment by Th1nkK1D** [comment]
So if anyone wants to contribute to this. What can we do now is remove the whole section in the red box from the home page https://parliamentwatch.wevis.info/

![image](https://github.com/user-attachments/assets/0c74fa21-6311-4859-bb83-8216b0c38380)

- Remove related UI from `src/routes/+page.svelte`
- Remove related data  `src/routes/+page.server.ts`
- Other related code from other files that won't be used anymore.

**Comment by bact** [comment]
Thank you. Take down may be the best option for now.

**Comment by Th1nkK1D** [comment]
Resolve in 2fd51283832f737ef29e3b905393606a9d4e311b
