### ISSUE TITLE
Navbar on mobile does not close when changing to new page

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#151]
**Describe the bug**
When clicking a link in the navbar on a mobile screen, the user thinks the page has not changed because it was hidden under the full-screen navbar menu.

**To Reproduce**
1. Go to any page eg. https://parliamentwatch.wevis.info
2. Click on the hamburger menu to open the menu.
3. Click any link to go to any page.
4. The page is changed in the background, but it is not visible because the menu is still there.

**Expected behavior**
When user click the link, the navbar menu should be closed so users can see the pages has changed.

**Screenshots**

[Screencast from 2024-10-24 18-12-53.webm](https://github.com/user-attachments/assets/83318469-9c03-4d83-a857-6f5886b2278a)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox (capture on responsive mode)

**Additional context**
- Navigation bar component: `src/components/NavigationBar/NavigationBar.svelte`

**Comment by SupeemAFK** [comment]
I can fix this if anyone hasn't done this yet.
