### ISSUE TITLE
Legislative Process Page: Body Skeleton

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#20]
![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/c4afaa48-eb22-42ed-bbdc-caee221fb18c)

View [Figma file](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?type=design&node-id=319-155076&mode=dev)

## Scope of work
- Add a Blue Title section. Use the current timestamp for the updated date for now.
- Don't need to do the sidebar. (Splitted into another issue #28 )
- No need to add the top breadcrumb.
- Add every heading 1 and heading 2 text, that shows on the sidebar, to the body but don't add other content yet.
  - Add styles and spacing in a way that content in each section can be added separately without concerning the body layout.  
- The body should be responsive. Desktop size should have `max-width` for the body (use the size from Figma) so that the paragraph shouldn't be too long.

## Starting point
- The page will be at the URL `/legislative-process`. The route file is located at src/routes/legislative-process/+page.svelte.

**Comment by Icyscools** [comment]
Hi, can I work on this?

**Comment by Th1nkK1D** [comment]
Merged #30
