### ISSUE TITLE
BillStatusTag Component

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#21]
![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/6d21c7a7-6ef8-4431-9e74-fd4b68c900d5)

View [Figma file](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?type=design&node-id=672-92178&mode=dev)

## Starting point

- Create a new component with `yarn gen:component`
- Can develop the component in Histoire with yarn story:dev
- Add the following props:
  - **status: BillStatus** defined in `src/models/bill.ts`
  - **isLarge: boolean** If `true`, show the large variation. (default = `false` = small)
- Don't forget to write Histoire's story.
  - Put 4 statuses in different `Hst.Variant` in grid layout ([see doc](https://histoire.dev/guide/svelte3/stories.html))
  - Add shared control for `isLarge` prop ([see doc](https://histoire.dev/guide/svelte3/controls.html))

**Comment by ptsgrn** [comment]
Can I do this one too?

**Comment by Th1nkK1D** [comment]
> Can I do this one too?

Sure! I think it's similar to your previous one ;)

**Comment by Th1nkK1D** [comment]
Merged #24
