### ISSUE TITLE
BillCategoryTag Component

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#22]
![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/c8cf1ed9-774f-4760-96b4-fbdead2bc569)

[View Figma file](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?type=design&node-id=1236-36604&mode=dev)

## Starting point

- Create a new component with `yarn gen:component`
- Can develop the component in Histoire with yarn story:dev
- Add the following props:
  - **label: string**
  - **isLarge: boolean** If `true`, show the large variation. (default = `false` = small)
- Don't forget to write Histoire's story. Add control for both props ([see doc](https://histoire.dev/guide/svelte3/controls.html))

**Comment by Annerez** [comment]
Can I do this? I have never participate in open source before but I'll try my best!

**Comment by Th1nkK1D** [comment]
> Can I do this? I have never participate in open source before but I'll try my best!

Sure! Please let us know if you need any help :)

**Comment by Annerez** [comment]
I accidentally unassign myself, can you assign me back? Sorry for your inconvenience.
