### ISSUE TITLE
Add this open source project into `Bangkok Open Source Festival '23`

### ISSUE THREAD

**Issue by pavaris-pm** [wevisdemo/parliament-watch#25]
I bring this issue up in order to inform you that i've added this repo to **Bangkok Open Source Festival '23** event since i think that your project can help a lot of people interesting in Thai Parliament. That is a very important factor nowadays. 

I think adding this repo to the event will help promoting it to others people and contributors to bring more interesting works into your repo. You can take a look at the event repo here [Bangkok Open Source Festival '23 repository](https://github.com/creatorsgarten/open.source.in.th), and your project will be shown in the [event website](https://open.source.in.th/) here.

Thanks for making this thing up so far! i will help contributing to `Parliament Watch` as well.

**Comment by Th1nkK1D** [comment]
That's fast! I saw the campaign yesterday and planned to join today. Thank you for adding our project. I might open the PR to update the text a bit.  🙏

**Comment by pavaris-pm** [comment]
You're welcome! Hope that you will keep doing it along 🎉.

**Comment by Th1nkK1D** [comment]
Hey, Thank you for promoting us to the Bangkok Open Source Festival '23! Please fill up the [form](https://airtable.com/appgGYIo458vDkrQN/shrZMe2hZBa6tQXvz) before 6 November 2023 to receive our limited-edition stickers.
