### ISSUE TITLE
BillCard Component

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#26]
![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/4e81fce2-5de6-431e-90b5-8b0919b6a721)

View [Figma file](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?type=design&node-id=672-92178&mode=dev)

## Depended on
- #21 
_Can do other parts of the component first if the issue is not closed yet_

## Starting point

- Create a new component with `yarn gen:component`
- Can develop the component in Histoire with yarn story:dev
- Add the following props:
  - `orientation: 'landscape' | 'portrait'`  default = 'landscape'
  - `nickname: string`
  - `title: string` (ชื่อทางการ)
  - `proposedBy: { avatar: string, name: string, description: string }`
  - `proposedOn: Date`
  - `status: BillStatus` defined in `src/models/bill.ts`
  - `currentState: string | undefined`
  - `daySinceProposed: number` 
  - `billUrl: string`
- Don't forget to write Histoire's story.
  - Mock data according to Figma. Use placeholder image from https://placehold.co. Use `#` for `billUrl` for now.
  - Put both orientations in different `Hst.Variant` in grid layout ([see doc](https://histoire.dev/guide/svelte3/stories.html))
  - Add shared control for all the props (except orientation) ([see doc](https://histoire.dev/guide/svelte3/controls.html))

**Comment by takeshikriang** [comment]
Hi there, can I work on this one?

**Comment by takeshikriang** [comment]
@Th1nkK1D It looks like the card is clickable.
Can we click on the entire card or just a specific part of it?

**Comment by Th1nkK1D** [comment]
> @Th1nkK1D It looks like the card is clickable. Can we click on the entire card or just a specific part of it?

The entire card can be clicked, that why the hover state changes the color of the whole card ;)

**Comment by Th1nkK1D** [comment]
Merged #32
