### ISSUE TITLE
Legistrative Process Page: Sidebar

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#28]
![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/d765432f-514f-4315-be47-05d3ff089415)

View [Figma file](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?type=design&node-id=319-155076&mode=dev)

## Depended on
- #20 
_Can do the component first if the issue is not closed yet_

## Scope of work
- Add all the headings and subheadings according to the design.
- Ignore the active indicator, for now, treat every item on the sidebar as a normal item.
- Might need to wait for #20 to be completed first to do:
  - Smooth scroll to each section on the body when clicking on the corresponding heading.
  - Responsive layout for both desktop/mobile screens.

## Starting point
- Create a new component file at `src/components/legislative-process/Sidebar.svelte`.
- The carbon design system has [SideNav in UI Shell](https://carbon-components-svelte.onrender.com/components/UIShell#header-with-side-navigation) I'm not sure if it will fit our use case. If not, we might need to create it from scratch.
- The component should be used in the `/legislative-process` page. The route file is located at `src/routes/legislative-process/+page.svelte`.

**Comment by thasarito** [comment]
can i take this issue?

**Comment by Th1nkK1D** [comment]
Merged #37
