### ISSUE TITLE
NavigationBar Component

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#3]
![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/4a87002f-6038-4b6b-ac08-a10cbfbeb9b0)

View [Figma file](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?node-id=40%3A67247&mode=dev)

## Scope of work
- You don't need to add a link to each menu yet.
- The search function doesn't need to work yet. Only focus on the UI.
- Blue/Purple announcement banner is not a part of this issue

## Starting point
- Create a new component with `yarn gen:component`
- Can develop the component in Histoire with `yarn story:dev`
- Logo is in `/static/images/logo`
- Don't start from scratch, take a look at [Carbon's UI Shell](https://carbon-components-svelte.onrender.com/components/UIShell#header-with-global-search)

**Comment by kodaicoder** [comment]
Can I do tis one ?
but may be will take some time on it
first time using Carbon and as a contributor 😉

**Comment by Th1nkK1D** [comment]
> Can I do tis one ?
> but may be will take some time on it
> first time using Carbon and as a contributor 😉

Sure! Take your time and feel free to ask if you have any questions 🙌

**Comment by kodaicoder** [comment]
Is I need to build a component on light theme too ? (white background , black text)

**Comment by kodaicoder** [comment]
It has so many buggy thing in UI Shell of Carbon component for Svelte
![image](https://github.com/wevisdemo/parliament-watch/assets/110652592/69dc6753-c394-41db-b869-916d9f2338e4)
 alignment of magnify icon and closing icon is not on a vertical center
 
![image](https://github.com/wevisdemo/parliament-watch/assets/110652592/362ad900-85b1-4243-a7f8-0c1fbb5384b9)
![image](https://github.com/wevisdemo/parliament-watch/assets/110652592/05a260b7-3c76-4108-9bbb-aa3ae5b0465f)

even you setting a sidebar of header to 'false' it still showing (this wired bug is still showing on [official demo site](https://carbon-components-svelte.onrender.com/framed/UIShell/HeaderNav?theme=g80) too )

[No Typedefs](https://carbon-components-svelte.onrender.com/components/UIShell#typedefs)

![image](https://github.com/wevisdemo/parliament-watch/assets/110652592/87c713b9-d0da-47db-be2c-849844dc5eac)
support only dark mode (for now)

may be I will considered to build it from scratch.

**Comment by Th1nkK1D** [comment]
Hmmm that worse than I expected 🥹

> may be I will considered to build it from scratch.

That might be the best way to go but I think this issue will be too big. How much have you already done? Tomorrow I'll take a look again and try to split into several smaller issues. Then you can pick one part of it that will not be too big.

**Comment by kodaicoder** [comment]
I Just only implement main header with logo, side menu button and side navigation (doesn't completed yet)

**Comment by kodaicoder** [comment]
#17

**Comment by Th1nkK1D** [comment]
That's awesome! Don't hesitate to let me know if you struck somewhere.

One suggestion, can you put `[WIP]` in front of the PR title, meaning that it is still a work in progress? So that when you remove the WIP, I will know that I can review the PR. ;)

**Comment by kodaicoder** [comment]
I has created new PR already , side menu is finish but may be have some rough edged on code , please review on that again
next I will try build a menu on desktop size.

**Comment by kodaicoder** [comment]
I fixed header nav and side menu to always shown if body is scrolled
and adding feature to hide a header nav and side menu while user scrolling down and showing after user scrolling up,
that mean even if user opening side menu and try scrolling down it will made deactivate side menu , if user want to open side menu again user need to scrolling up and press a side menu button again.

**Comment by Th1nkK1D** [comment]
Hi! your progress looks very promising. However, can you use only one PR for this issue? Because I'm not sure how to review separated PRs on the same component. Right now we have #17 and #18 which both refer to this issue. 🙏

**Comment by Th1nkK1D** [comment]
> Is I need to build a component on a light theme too? (white background, black text)

Sorry, I missed this comment. You don't need to implement the theme. We won't change the theme on this project.

**Comment by kodaicoder** [comment]
> Hi! your progress looks very promising. However, can you use only one PR for this issue? Because I'm not sure how to review separated PRs on the same component. Right now we have #17 and #18 which both refer to this issue. 🙏

sorry about duplicated PR on same component , at first I forget to create a new branch of component in my forked project (this is PR #17)  and after that I has created a branch for the component (PR #19 (I cancel PR for #18 already))

I need to cancel PR #17 then ?

**Comment by kodaicoder** [comment]
I don't sure is this allow
I need to adding some config in ` vite.config.ts` 
the config is to adding static folder to allow list
using this code after plugin section
` server: {
		fs: {
			allow: ['./static']
		}
}` 

because if I don't do this while I using `import logoLong from '/static/images/logo/pw-long-white.png';` 
this will return as a http error code `403 Restricted` as image below

![image](https://github.com/wevisdemo/parliament-watch/assets/110652592/3e6db3e5-8165-4793-bd54-0475ce7ddd2b)

**Comment by Th1nkK1D** [comment]
> because if I don't do this while I using `import logoLong from '/static/images/logo/pw-long-white.png';` this will return as a http error code `403 Restricted` as image below

I think it's because of the path. When the path starts with `/` it will look at the root of your computer, not the root of our project. Try to use the relative path that starts with the folder name or use `../` to go up from the current directory.

I guess that the file you are working in is in the folder `src/components/NavigationBar` to address the logo in the relative path you might want to use `../../../static/images/logo/pw-long-white.png`

**Comment by Th1nkK1D** [comment]
> I guess that the file you are working in is in the folder `src/components/NavigationBar` to address the logo in the relative path you might want to use `../../../static/images/logo/pw-long-white.png`

My bad regarding the image issue. SvelteKit serves everything in the `static` folder at the root `/` when you run the dev server or build, but that is not the case with Histoire. In the commit 0573301789b01fb71ae3e1363534224ea3f3d0ee of the main branch, I config histoire to serve files in the `static` folder as well. So now you don't need to use `import`, you just set `src="/images/logo/pw-long-white.png"` and it's gonna work both in SveltKit and Histoire.

You can just add this line in your branch, cherry-pick, or merge from the main branch to get this function to work.

**Comment by kodaicoder** [comment]
Component is complete 🥳🥳🥳
please review it in PR 

Thank you.

**Comment by Th1nkK1D** [comment]
Merged #19 🎉
