### ISSUE TITLE
Incorrect DataPage's filter and NavigationBar z-index alignment

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#38]
## Step to reproduce
1. Open https://parliament-watch.pages.dev/politicians/สมชาติ-สกุลสมมุติ/votes in the mobile screen size of responsive mode

## Current incorrect behaviors
1. Filter button in the bottom left is barely visible. The background is missing. (This one also occurs in desktop size)
![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/f4ef9c5b-9da2-4f93-bc4d-7cf9d4528a2c)

2. When opening the hamburger menu, the filter button is still showing. 

[Screencast from 2023-10-19 14-41-15.webm](https://github.com/wevisdemo/parliament-watch/assets/8860448/9a904c5d-0e79-421c-8953-7c9b99d0df5c)

3. The navigation bar is in front of the filter panel, which hides the search box and close button.

[Screencast from 2023-10-19 14-45-35.webm](https://github.com/wevisdemo/parliament-watch/assets/8860448/e33ae33d-0d23-4770-9499-273bdc8719ac)

_Tested on Firefox and Chromium on Linux_

## Expectation
1. The filter button should have `interactive-01` color. [(See Figma)](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?type=design&node-id=1009-247263&mode=dev)
2. The sidebar opened with the hamburger menu should be in front of the filter button.
3. The filter panel should be in front of the navigation bar

## Starting point
1. **DataPage component** (contain the filter button and panel) [src/components/DataPage/DataPage.svelte](src/components/DataPage/DataPage.svelte)
2. **NavigationBar component** (contain the hamburger menu and sidebar) [src/components/NavigationBar/NavigationBar.svelte](src/components/NavigationBar/NavigationBar.svelte)

**Comment by loukhin** [comment]
Hi, can I work on this?

**Comment by loukhin** [comment]
Updating `z-index` of filter panel solve the issue on mobile screen. However, on desktop, the filter panel will be in front of the navigation bar.

What do we want to do in this case?

[Kapture 2023-10-21 at 12.14.44 2.webm](https://github.com/wevisdemo/parliament-watch/assets/29707893/612fba75-ec9f-4404-8978-cd2215c1b6cf)

**Comment by Th1nkK1D** [comment]
> Updating `z-index` of filter panel solve the issue on mobile screen. However, on desktop, the filter panel will be in front of the navigation bar.
> 
> We can apply the `z-index` only when on mobile screen, but the navigation bar is still in front of the filter panel on desktop.
> 
> What do we want to do in this case?

Good catch. On the mobile, the filter should be in front of the navbar because it acts like a fullscreen pop-up. But on the desktop, filter should be behind the navbar because it's just an element in the body.

**Comment by loukhin** [comment]
> Good catch. On the mobile, the filter should be in front of the navbar because it acts like a fullscreen pop-up. But on the desktop, filter should be behind the navbar because it's just an element in the body.

If we leave the filter panel behind the navigation bar then we need to scroll down if we want to filter/close filter panel, is that acceptable?

**Comment by loukhin** [comment]
I try experimenting with the header show/hide logic, what do you think?

What it's currently look like:

[Kapture 2023-10-21 at 14.58.23.webm](https://github.com/wevisdemo/parliament-watch/assets/29707893/9288c179-fbe7-4122-893a-99c722fb1ac5)

What's my experiment look like:

[Kapture 2023-10-21 at 14.53.22.webm](https://github.com/wevisdemo/parliament-watch/assets/29707893/c9000fba-d50f-4baa-80f8-a4b23ccc5786)

**Comment by Th1nkK1D** [comment]
> I try experimenting with using the header show/hide logic to determine filter input location, what do you think?

Oh yeah, I forget that navbar behavior. Love your solution. It looks so smooth 🔥
