### ISSUE TITLE
Footer Component

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#4]
![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/ca32e29f-2bdf-470d-a304-c9374ddb6c08)

See [Figma file](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?node-id=40%3A67247&mode=dev)

## Scope of Work
- Scroll to top floating button is not a part of this issue

## Starting point
- Create a new component with `yarn gen:component`
- Can develop the component in Histoire with `yarn story:dev`
- Logo is in `/static/images/logo`
- Some icons are already available in `src/components/icons` (available in Histoire as well).

**Comment by infinindy** [comment]
I'm interested in this issue kub.

**Comment by badgooooor** [comment]
Hi, can I take this?

**Comment by Th1nkK1D** [comment]
Merged #15
