### ISSUE TITLE
Legislative process content 2/9: Bill type 

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#41]
## Scope

Only what is included in the screenshot

![Screenshot_20231021-094833.png](https://github.com/wevisdemo/parliament-watch/assets/8860448/f40163b4-1fc4-4050-8915-47ebca08bd3a)

[View Figma](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?node-id=154%3A63562&mode=dev)

## Starting point

1. The page is available at /legislative-process (source: `srv/routes/legislative-process`)
2. Put the content under the right heading.
3. If there are images, export from Figma, optimize images with squoosh.app or ImageOptim, put it in `/static/images/legislative-process` with a meaning full name.
4. If there is a duplicate UI, create a new component and put it in `src/components/legislative-process`

**Comment by mdechdee** [comment]
I'll try contribute this one krub, do I have to include interactivity (click to expand)?

**Comment by Th1nkK1D** [comment]
> I'll try contribute this one krub, do I have to include interactivity (click to expand)?

Yes. I suggest creating a new component for this expandable accordion. Please let me know if you run into any problems ;)

**Comment by Th1nkK1D** [comment]
Hi, if you run into an issue that `<b>` won't make the text bold. It is fixed in c572545cbeb7c13fbd836130ca871a4453d47f85 so please pull the latest commit from the main branch.

**Comment by Th1nkK1D** [comment]
Merged #54
