### ISSUE TITLE
Legislative process content 3/9: Bill status

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#42]
## Scope

Only what is included in the screenshot

![Screenshot_20231021-094907.png](https://github.com/wevisdemo/parliament-watch/assets/8860448/7aa7b3f9-ac2b-480e-9832-189d5f0b7f84)

[View Figma](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?node-id=154%3A63562&mode=dev)

## Starting point

1. The page is available at /legislative-process (source: `srv/routes/legislative-process`)
2. Put the content under the right heading.
3. If there are images, export from Figma, optimize images with squoosh.app or ImageOptim, put it in `/static/images/legislative-process` with a meaning full name.
4. If there is a duplicate UI, create a new component and put it in `src/components/legislative-process`

**Comment by l3luescreen** [comment]
Hi, Can I work on this one?

**Comment by Th1nkK1D** [comment]
Hi, if you run into an issue that `<b>` won't make the text bold. It is fixed in c572545cbeb7c13fbd836130ca871a4453d47f85 so please pull the latest commit from the main branch.

**Comment by l3luescreen** [comment]
Hi, I saw some of bold texts used `font-weight: 600` in Figma. But styles in typography provide `font-weight: 700`. Should I follow typography or Figma?

<img width="950" alt="Screenshot 2566-10-29 at 00 10 46" src="https://github.com/wevisdemo/parliament-watch/assets/42911520/74169809-0063-4d2d-97a5-de29e8cf0865">

<img width="517" alt="Screenshot 2566-10-29 at 00 24 57" src="https://github.com/wevisdemo/parliament-watch/assets/42911520/f0ca9096-7593-4479-8867-dc1557606441">


This is `font-weight: 600`
<img width="407" alt="Screenshot 2566-10-29 at 00 12 00" src="https://github.com/wevisdemo/parliament-watch/assets/42911520/4dc23438-e10a-4fd7-9745-ae7a4026be40">

This is `font-weight: 700`
<img width="363" alt="Screenshot 2566-10-29 at 00 12 34" src="https://github.com/wevisdemo/parliament-watch/assets/42911520/3f56ff72-296a-476c-bada-6c188de0d6d8">

**Comment by Th1nkK1D** [comment]
> Hi, I saw some of bold texts used `font-weight: 600` in Figma. But styles in typography provide `font-weight: 700`. Should I follow typography or Figma?

Sorry for the confusion, we have 2 headings set for typography. This one here is the `fixed-heading` which we refer to it as `heading`, not a `fluid-heading` that is responsive.

![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/40e2ff37-4eb2-49f3-ab60-ff4514bacd72)
![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/23fcc408-8900-43f7-89ff-adbc7aafcf4f)

So you can add a font-weight of 600 according to Figma. I think for tailwind it is `font-semibold`.

**Comment by Th1nkK1D** [comment]
Merged #59
