### ISSUE TITLE
Legislative process content 7/9: Voting process

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#46]
## Scope

Only what is included in the screenshot

![Screenshot_20231021-095151.png](https://github.com/wevisdemo/parliament-watch/assets/8860448/9a3e48d8-7e16-423a-b129-c232cd9caacb)

[View Figma](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?node-id=154%3A63562&mode=dev)

## Starting point

1. The page is available at /legislative-process (source: `srv/routes/legislative-process`)
2. Put the content under the right heading.
3. If there are images, export from Figma, optimize images with squoosh.app or ImageOptim, put it in `/static/images/legislative-process` with a meaning full name.
4. If there is a duplicate UI, create a new component and put it in `src/components/legislative-process`

**Comment by kodaicoder** [comment]
Can I take this one ?
Is it static data ?

**Comment by Th1nkK1D** [comment]
> Can I take this one ? Is it static data ?

Sure! And everything is static.
