### ISSUE TITLE
Legislative process content 8/9: Voting type and result

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#47]
## Scope

Only what is included in the screenshot

![Screenshot_20231021-095217.png](https://github.com/wevisdemo/parliament-watch/assets/8860448/31e2190b-30f3-439f-9458-389e351dfdca)

[View Figma](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?node-id=154%3A63562&mode=dev)

## Starting point

1. The page is available at /legislative-process (source: `srv/routes/legislative-process`)
2. Put the content under the right heading.
3. If there are images, export from Figma, optimize images with squoosh.app or ImageOptim, put it in `/static/images/legislative-process` with a meaning full name.
4. If there is a duplicate UI, create a new component and put it in `src/components/legislative-process`

**Comment by tortrakul-won** [comment]
Hi, I think I can do this one. Can I contribute to this issue?

If so, may I know the deadline?

**Comment by tortrakul-won** [comment]
![image](https://github.com/wevisdemo/parliament-watch/assets/136137961/1a2416a9-a3ad-4757-8866-995c4882f55c)

Are these supposed to be list items `<li>`? The way they read is a bit unusual.

**Comment by Th1nkK1D** [comment]
> Are these supposed to be list items `<li>`? The way they read is a bit unusual.

Yup it's `li` but in 2 column as a separated list. One for 'ไม่ลงคะแนน' and one for 'ลา/ขาดลงมติ'

**Comment by tortrakul-won** [comment]
This might be a stupid question but I can't seem to create a new branch?

**Comment by Th1nkK1D** [comment]
> This might be a stupid question, but I can't seem to create a new branch. Can you help me with this?

Without permission, no one except the owner can push a commit or create a new branch to the repo. This is for security reasons. You need to folk first, push to your own forked repo, then open the pull request. After that I can review and merge our repo.

**Comment by Th1nkK1D** [comment]
Merged #56
