### ISSUE TITLE
Legislative process content 9/9: Representatives and Senates 

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#48]
## Scope

Only what is included in the screenshot

![Screenshot_20231021-095258.png](https://github.com/wevisdemo/parliament-watch/assets/8860448/d1003900-53bd-41f9-ba7c-358da8d63353)

[View Figma](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?node-id=154%3A63562&mode=dev)

## Starting point

1. The page is available at /legislative-process (source: `srv/routes/legislative-process`)
2. Put the content under the right heading.
3. If there are images, export from Figma, optimize images with squoosh.app or ImageOptim, put it in `/static/images/legislative-process` with a meaning full name.
4. If there is a duplicate UI, create a new component and put it in `src/components/legislative-process`

**Comment by pontakornth** [comment]
I can do this one.

**Comment by Th1nkK1D** [comment]
Merged #50
