### ISSUE TITLE
VoteCard Component

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#5]
![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/6cfe4f5b-2a43-4c2d-b001-ddabe864a887)

[See Figma file](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?type=design&node-id=801-120090&mode=dev)

## Starting point
- Create a new component with `yarn gen:component`
- Can develop the component in Histoire with `yarn story:dev`
- Should have `voting` and `highlightedVoteByGroups` props which are the same type as described in the `Interface VoteCard` in `src/routes/assemblies/[id]/+page.ts`
- 3 variations from the design depend on `voting.result`, either if it's `DefaultVotingResult.Passed`, `DefaultVotingResult.Failed`, or any `string`

**Comment by fResult** [comment]
I wanna do this issue krub 🙂

**Comment by fResult** [comment]
![image](https://github.com/wevisdemo/parliament-watch/assets/19329932/15a65921-0cdb-4947-87c7-846cd58022af)
https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?node-id=1431%3A42175&mode=dev

Where can I get these mock data krub?  
I see `passedVoting` variable in the [`src/mocks/data/voting.ts`](https://github.com/wevisdemo/parliament-watch/blob/52efa4157d23739f28f3e959c77b0a911a2d354b/src/mocks/data/voting.ts) file, but I have no idea how to get data same as in the Figma.

**Comment by fResult** [comment]
Finished krub
![image](https://github.com/wevisdemo/parliament-watch/assets/19329932/fd0510a6-5ee1-4bdc-aeed-74c6e1196dd2)

https://github.com/wevisdemo/parliament-watch/issues/5

**Comment by fResult** [comment]
Finished krub

![VoteCard.story.svelte file](https://github.com/wevisdemo/parliament-watch/assets/19329932/fd0510a6-5ee1-4bdc-aeed-74c6e1196dd2)

**Comment by Th1nkK1D** [comment]
Merged #8
