### ISSUE TITLE
Highlight active section on scroll in legistrative process sidebar 

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#53]
![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/46a44c35-5a6f-4208-88f3-71ce58f59a35)

[View Figma](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?type=design&node-id=412-164715&mode=dev)

## Starting point

- The `Sidebar` component was already implemented in /legislative-process page (source: `src/routes/legislative-process/+page.svelte`).
- Add a logic that when user scroll into each section, the item in side bar is highlighted (like `แนะนำภาพรวม` from the screenshot) 
  - Can use `scrollama` to detect the section. See example in `src/routes/politicians/[id]/+page.svelte` that implement similar thing.
  - Try `isSelected` props on the `SideMenuItem` component [ref](https://carbon-components-svelte.onrender.com/components/UIShell)

**Comment by ptsgrn** [comment]
Hello again! Can I do this as my 3rd PR?

**Comment by Th1nkK1D** [comment]
@ptsgrn Hi any update regarding this? Please let me know if you don't have a plan to do it soon so I can pass this issue to another person.

**Comment by ptsgrn** [comment]
I'm deeply sorry, @Th1nkK1D, to say that I think I will no longer be working on this. Due to its complexity and my own limited availability, you can safely assign it to someone else. I deeply apologize for not addressing this issue promptly and for not completing it.

**Comment by Th1nkK1D** [comment]
@ptsgrn don't worry! And please fill out the [form](https://airtable.com/appgGYIo458vDkrQN/shrZMe2hZBa6tQXvz) so we can send you a sticker for your previous contribution 🙌

**Comment by svnnynior** [comment]
hi hi, can i do this? :)

**Comment by Th1nkK1D** [comment]
Merged #64
