### ISSUE TITLE
PoliticianProfile Component

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#6]
![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/7984fa85-84c5-4a6b-99f2-bdf5d8ec7abc)

See [Figma file](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?type=design&node-id=670-55561&mode=dev)

## Scope of Work
- label "ประธานสภา" is not under this issue's scope

## Starting point
- Create a new component with `yarn gen:component`
- Can develop the component in Histoire with `yarn story:dev`
- Component would has the following props:
  - `id`, `firstname`, `lastname`, `avatar` as a string
  - `party` as a Party
  - `role` as a string
  - `isLarge` as a boolean, to switch between the variation (default = false = small)

**Comment by infinindy** [comment]
I'm interested in this issue kub.

**Comment by droppdeadz** [comment]
I'll do this issue krub

**Comment by Th1nkK1D** [comment]
Merged #11
