### ISSUE TITLE
BackToTopButton Component

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#7]
![image](https://github.com/wevisdemo/parliament-watch/assets/8860448/3fb6e460-fcb8-465b-9462-280f0e1e6e95)

See [Figma file](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?type=design&node-id=839-167422&mode=dev)

## Starting point
- Create a new component with `yarn gen:component`
- Can develop the component in Histoire with `yarn story:dev`
- The button should be hidden when the user is already at the top.
- When the user is not at the top, floating as a position fix at the bottom right corner. Refer to the margin [here](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?type=design&node-id=1327-103605&mode=dev)
- When clicked, smoothly scroll the page to the top.

**Comment by tee4cute** [comment]
This one seems to be an easiest one. Can I start with this one?
Ps. It's the very first time for me in using Svelte & Tailwind. So, I think that you can assign this issue to another (more proficient) contributor if there is someone going to take it. I just want to join the project for fun, but, for real contribution also  :).

**Comment by tee4cute** [comment]
I've finished this!!! I think it's ready for PR. But, I cannot push the code to remote repo. Permission Denied >.<.

**Comment by Th1nkK1D** [comment]
Merged #9
