### ISSUE TITLE
Add UI for cabinet assembly changes pages

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/parliament-watch#84]
This is a huge issue and requires some experimentation. Please read carefully.

![image](https://github.com/user-attachments/assets/d495253e-3649-463a-8665-225cbf5aa151)

View [Figma file](https://www.figma.com/design/mDfjhPaHtIIoI3D9wP3iwF/Design_Phase02-%5BThe-Cabinet%5D?node-id=255-29751&t=W44LRnInLc0KHQ4U-4) for more detail brief

## Notes
- Starting route file: `src/routes/assemblies/[id]/changes/+page.svelte`. Currently has no UI, just the data prepared by adjacent `+page.server.ts`
   - `assembly` = assembly info
   - `availableAssemblies` = list of all assemblies to create a navigation link
   - `assemblyRoles` = list of every combination of politicians (id) and their role in the current assembly (one politician can have more than one role. This is the correct behavior. The member list in the main assembly page is incorrect since current logic removes duplicated politicians, but fixing it is out of this issue's scope)
   - `members` politician information that exists in  `assemblyRoles` 
- This page should be available only for cabinet. you can use path `/assemblies/คณะรัฐมนตรี-63/changes` for testing.
- The main logic is to sync **selected date** between the bar chart, date picker, members tabs, and the timeline tab.
- Try to reuse previously created components including #78, and #80, components used in assembly pages or others. Can make some changes if necessary.
- Some parts of the design have not yet validated the technical feasibility. **If you find something impossible or too complicated to implement, you can suggest an alternative solution or ask for discussion**

**Comment by Th1nkK1D** [comment]
@JaeAiKay ฝากอันนี้ไว้ในช่วงที่เราไม่อยู่จนถึงวันที่ 5 ส.ค. ลองอ่านดู ทำเท่าที่ได้ ตรงไหนติดเดี๋ยวกลับมาช่วย ละในฐานะที่ทำมาหลาย PR ละเราฝากบรีฟวิธีการทำงาน และแบ่งงานใน issue นี้กับ @napatswift หน่อย (บ่นอยากทำงาน เรา invite เข้า repo ไปแล้วโปรด accept) ทำใน branch เดียวกันเลยก็ได้ละเปิด PR มาทีเดียว

ฝาก assign ชื่อตัวเองเข้า issue นี้ทั้งคู่เลย กราบขอบพระคุณเป็นอย่างสูง

**Comment by JaeAiKay** [comment]
รับแซ่บบบ

**Comment by napatswift** [comment]
@Th1nkK1D @JaeAiKay  มีคำถามเรื่อง tab หน่อยครับ เท่าที่ผมลองดูใน repo นี้ในหน้า `assemblies/[id]/members/` มีการใช้ [tab](https://github.com/wevisdemo/parliament-watch/blob/main/src/components/Assemblies/Members/Tab.svelte) แต่ไม่ใช่การเปลี่ยน tab โดยการใช้ state แต่เป็นการเปลี่ยน path ไปที่ tab view นั้น เลยอยากรู้ว่าอยากให้ทำท่าเดียวกันดีไหมครับ

**Comment by Th1nkK1D** [comment]
> @Th1nkK1D @JaeAiKay  มีคำถามเรื่อง tab หน่อยครับ เท่าที่ผมลองดูใน repo นี้ในหน้า `assemblies/[id]/members/` มีการใช้ [tab](https://github.com/wevisdemo/parliament-watch/blob/main/src/components/Assemblies/Members/Tab.svelte) แต่ไม่ใช่การเปลี่ยน tab โดยการใช้ state แต่เป็นการเปลี่ยน path ไปที่ tab view นั้น เลยอยากรู้ว่าอยากให้ทำท่าเดียวกันดีไหมครับ

ในกรณีนี้ดีไซน์อยากให้ทั้ง 2 แท็บและ control ข้างบน sync กันหมด สมาชิกในแท็บแรกต้องเป็นของ ณ วันที่เลือก และวันนั้นต้องไฮไลท์ในไทม์ไลน์การเปลี่ยนแปลงในแท็บที่สอง มองซะว่าเป็น 2 view ที่แสดงมาจาก state เดียวกัน เพราะงั้นเราแยกหน้าบ่ได้ เปลี่ยนแท็บแล้ววันที่เลือกจะหาย

**Comment by napatswift** [comment]
ถ้าเราเก็บทั้ง tab ทั้งวันให้อยู่ใน path หรือ url params ก็ไม่ได้ใช่ไหมครับ เหมือนมันจะต้อง generate path ตอน build (รึเปล่า)

**Comment by Th1nkK1D** [comment]
> ถ้าเราเก็บทั้ง tab ทั้งวันให้อยู่ใน path หรือ url params ก็ไม่ได้ใช่ไหมครับ เหมือนมันจะต้อง generate path ตอน build (รึเปล่า)

ใช่แล้ว คิดว่าไม่ต้องทำอะไรเกี่ยวกับ path/param เลยสำหรับ issue นี้ เป็นหน้าเดียวไปได้เลยแล้วเก็บ state เอา

**Comment by napatswift** [comment]
สุดแจ่ม
