### ISSUE TITLE
Promise: List Component

### ISSUE THREAD

**Issue by mixth** [wevisdemo/parliament-watch#96]
The PR shall be merged into `promise/main` branch.

# Purpose
The component will be used to present `PromiseCard` for any specific filters both in `/promises` and `/promises/explore` page.

# Suggested props
- summaries: PromiseSummary[]
- cappedAt: number | undefined

```ts
interface PromiseSummary
  extends Pick<
    Promise,
    | 'id',
    | 'statements',
    | 'party',
    | 'keywords',
    | 'categories',
    | 'status',
      {
    latestProgressDate: date,
}
```

# UI

Please refer to [latest UI in Figma](https://www.figma.com/design/ywiKyd0XIgDXf8crX4aoYE/Design_Phase1-2-%5BPromise-Tracker%5D?node-id=4552-9015&node-type=frame&t=loPbqUyXBGsvLv1C-0) from the design team.

- This ticket does not include the list view. We'll address it in the later state.

![Frame 1510](https://github.com/user-attachments/assets/03ed2992-c0bc-4e20-90da-f84821dedc9e)

**Comment by Th1nkK1D** [comment]
Merged #107
