### ISSUE TITLE
Promise: Detail page

### ISSUE THREAD

**Issue by mixth** [wevisdemo/parliament-watch#98]
The PR shall be merged into `promise/main` branch.

# Purpose

To display statements, references, and progresses of the promise.

# Technical Note

- This page resides in `/promises/[id]`

# UI

- Clarification log section is out of scope for now.

Please refer to [the latest Figma](https://www.figma.com/design/ywiKyd0XIgDXf8crX4aoYE/Design_Phase1-2-%5BPromise-Tracker%5D?node-id=4552-8662&node-type=frame&t=loPbqUyXBGsvLv1C-0) by the design team.

![detail](https://github.com/user-attachments/assets/89653fcb-232b-420c-9fe7-c2a3e14a3b05)

**Comment by Th1nkK1D** [comment]
Merged #113
