### ISSUE TITLE
Promise: Home page

### ISSUE THREAD

**Issue by mixth** [wevisdemo/parliament-watch#99]
The PR shall be merged into `promise/main` branch.

# Purpose
To show an overview of the current cabinet's promises.

# Technical Note
This page resides in `/promises`

# UI
- This issue does not include the list component integration in the bottom which will be introduced by later ticket.

![home](https://github.com/user-attachments/assets/8d081138-6eef-4ef9-9ca7-bab82c9ae5cd)

**Comment by Th1nkK1D** [comment]
Merged #111
